runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/html/jp/index.html
  upload: www/html/jp/index.html

- url: /jp
  static_files: www/html/jp/index.html
  upload: www/html/jp/index.html

- url: /ca
  static_files: www/html/ca/index.html
  upload: www/html/ca/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
